package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"server/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	var user model.User
	err := r.DB.QueryRow(ctx, "INSERT INTO users (name) VALUES ($1) RETURNING id, name", input.Name).Scan(&user.ID, &user.Name)
	if err != nil {
		return nil, err
	}
	return &user, nil
}

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	var todo model.Todo
	err := r.DB.QueryRow(ctx, "INSERT INTO todos (text, done, user_id) VALUES ($1, $2, $3) RETURNING id, text, done, user_id", input.Text, false, input.UserID).Scan(&todo.ID, &todo.Text, &todo.Done, &todo.UserID)
	if err != nil {
		return nil, err
	}
	return &todo, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	usersQuery, err := r.DB.Query(ctx, "SELECT id, name FROM users")
	if err != nil {
		return nil, err
	}
	defer usersQuery.Close()

	var users []*model.User
	for usersQuery.Next() {
		var user model.User
		err := usersQuery.Scan(&user.ID, &user.Name)
		if err != nil {
			return nil, err
		}
		users = append(users, &user)
	}
	return users, nil
}

// To-dos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	todosQuery, err := r.DB.Query(ctx, "SELECT id, text, done, user_id FROM todos")
	if err != nil {
		return nil, err
	}
	defer todosQuery.Close()

	var todos []*model.Todo
	for todosQuery.Next() {
		var todo model.Todo
		err := todosQuery.Scan(&todo.ID, &todo.Text, &todo.Done, &todo.UserID)
		if err != nil {
			return nil, err
		}
		todos = append(todos, &todo)
	}

	return todos, nil
}

// To-dosByUser is the resolver for the todosByUser field.
func (r *queryResolver) TodosByUser(ctx context.Context, userID string) ([]*model.Todo, error) {
	todosQuery, err := r.DB.Query(ctx, "SELECT id, text, done, user_id FROM todos WHERE user_id = $1", userID)
	if err != nil {
		return nil, err
	}
	defer todosQuery.Close()

	var todos []*model.Todo
	for todosQuery.Next() {
		var todo model.Todo
		err := todosQuery.Scan(&todo.ID, &todo.Text, &todo.Done, &todo.UserID)
		if err != nil {
			return nil, err
		}
		todos = append(todos, &todo)
	}
	return todos, nil
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *model.Todo) (*model.User, error) {
	var user model.User
	err := r.DB.QueryRow(ctx, "SELECT id, name FROM users WHERE id = $1", obj.UserID).Scan(&user.ID, &user.Name)
	if err != nil {
		return nil, err
	}

	return &user, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
